.TH man 1 "19 Sep 2025" "0.1.0" "wlgamma man page"
.SH NAME
wlgamma \- gamma and color tint adjustment for Wayland compositors.
.SH SYNOPSIS
wlgamma [options]
.SH DESCRIPTION
wlgamma is a tool for adjusting color tint and gamma for Wayland compositors.
.SH OPTIONS
.TP
.B -h
Display help information.
.TP
.B -v
Display version information.
.TP
.B -l
List all Wayland outputs and exit.
.TP
.B -o index
Target a particular Wayland output.
.TP
.B -r value
Set the red channel multiplier (default: 1.0).
.TP
.B -g value
Set the green channel multiplier (default: 1.0).
.TP
.B -b value
Set the blue channel multiplier (default: 1.0).
.TP
.B -G value
Set the gamma (default: 1.0).
.SH BUGS
Please report all bugs at https://github.com/amini-allight/wlgamma/issues
.SH WWW
https://github.com/amini-allight/wlgamma
.SH AUTHOR
Amini Allight <amini.allight@protonmail.com>
.SH COPYRIGHT
Copyright (C) 2025 Amini Allight

wlgamma is free software; you can redistribute it and/or modify it under the terms of the GPL version 3 or later.
